# <center>Network Science</center>

## <center>Home Assignment #3: Centralities and Assortativity</center>

### <center>Student: *{Kosheleva Yevgeniya}*</center>

#### <hr /> General Information

**Due Date:** 13.03.2016 23:59 <br \>
**Late submission policy:** -0.2 points per day <br \>


Please send your reports to <mailto:network.hse.2016@gmail.com> with message subject of the following structure:<br \> **[HSE Networks 2015] *{LastName}* *{First Name}* HA*{Number}***

Support your computations with figures and comments. <br \>
If you are using IPython Notebook you may use this file as a starting point of your report.<br \>
<br \>
<hr \>

## Problems

### Task 1

Compute degree centrality, Pagerank and  HubAuthorities scores for the [flickr](https://snap.stanford.edu/data/web-flickr.html) network. 

Data contains sparse matrix A and list of user names.
This is a “denser” part of the Flickr photo sharing site friendship graph from 2006. Edge direction corresponds to friendship requests (following). Some of the links are reciprocal,others not.  

Provide top 50 names in each ranking, compare results

You can load .mat files with the following commands:

In [1]:
import scipy.io
import networkx as nx
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib
import operator
import pandas as pd
import scipy.spatial as spt
import numpy as np
import scipy.stats

Create graph:

In [2]:

data1 = scipy.io.loadmat('/Users/Evgenia/Desktop/Данные/flickr.mat')
G = nx.from_scipy_sparse_matrix(data1["A"],create_using=nx.DiGraph())

Compute the degree centrality:

In [3]:
degree_centrality = nx.degree_centrality(G)
sorted_degree = sorted(degree_centrality.items(), key=operator.itemgetter(1), reverse=True)[:50]

Compute the in-degree centrality for nodes:

In [4]:
in_degree_centrality = nx.in_degree_centrality(G)
sorted_in_degree = sorted(in_degree_centrality.items(), key=operator.itemgetter(1), reverse=True)[:50]

Compute the out-degree centrality for nodes:

In [5]:
out_degree_centrality = nx.out_degree_centrality(G)
sorted_out_degree = sorted(out_degree_centrality.items(), key=operator.itemgetter(1), reverse=True)[:50]

Return the PageRank of the nodes:

In [6]:
pr = nx.pagerank(G)
sorted_pr = sorted(pr.items(), key=operator.itemgetter(1), reverse=True)[:50]


Return HITS hubs and authorities values for nodes:

In [7]:
h,a = nx.hits(G)
sorted_h = sorted(h.items(), key=operator.itemgetter(1), reverse=True)[:50]
sorted_a = sorted(a.items(), key=operator.itemgetter(1), reverse=True)[:50]

In [8]:
df={"sorted_degree":[data1["names"][i[0]] for i in sorted_degree],"sorted_in_degree":[data1["names"][i[0]] for i in sorted_in_degree],\
    "sorted_out_degree":[data1["names"][i[0]] for i in sorted_out_degree],\
    "sorted_pr":[data1["names"][i[0]] for i in sorted_pr],
    "h":[data1["names"][i[0]] for i in sorted_h],"a":[data1["names"][i[0]] for i in sorted_a]}

In [9]:
df=pd.DataFrame(df,columns=["sorted_degree","sorted_in_degree","sorted_out_degree","sorted_pr","h","a"])
df.columns = ["degree centrality", "in degree centrality", "out degree centrality","PageRank","hubs","authorities"]
df

degree centrality  \
0   awfulsara                                     ...   
1   drp                                           ...   
2   DrJoanne                                      ...   
3   antimethod                                    ...   
4   *Ivan*                                        ...   
5   BombDog                                       ...   
6   deborah lattimore                             ...   
7   Simon Pais                                    ...   
8   cymagen                                       ...   
9   notraces                                      ...   
10  MaD Gi®L•™                               ...   
11  aleyna                                        ...   
12  *starlet*                                     ...   
13  lorrainemd                                    ...   
14  Pandarine                                     ...   
15  artofgold                                     ...   
16  :Nikola                                       ...   
17  Mareen Fischinger                             ...   
18  gu@va                                         ...   
19  Mylens                                        ...   
20  bernardo.borghetti                            ...   
21  hot_luscious                                  ...   
22  romanlily                                     ...   
23  jkottke                                       ...   
24  pixietart                                     ...   
25  slowernet                                     ...   
26  anildash                                      ...   
27  pbowers                                       ...   
28  Joi                                           ...   
29  fraying                                       ...   
30  naftalina007                                  ...   
31  .lush                                         ...   
32  Loobylu                                       ...   
33  Buntekuh                                      ...   
34  CherryVega                                    ...   
35  Gayla                                         ...   
36  jakedobkin                                    ...   
37  underbunny                                    ...   
38  fd                                            ...   
39  Airchild                                      ...   
40  maximolly                                     ...   
41  * HoNe$t *                                    ...   
42  Sexy Swedish Babe                             ...   
43  Ya Ya                                         ...   
44  kaneblues                                     ...   
45  Tsunami Notes                                 ...   
46  990000                                        ...   
47  overshadowed                                  ...   
48  Tom Coates                                    ...   
49  good morning stradivari                       ...   

                                 in degree centrality  \
0   awfulsara                                     ...   
1   drp                                           ...   
2   *Ivan*                                        ...   
3   antimethod                                    ...   
4   DrJoanne                                      ...   
5   BombDog                                       ...   
6   Simon Pais                                    ...   
7   deborah lattimore                             ...   
8   MaD Gi®L•™                               ...   
9   notraces                                      ...   
10  :Nikola                                       ...   
11  cymagen                                       ...   
12  aleyna                                        ...   
13  lorrainemd                                    ...   
14  artofgold                                     ...   
15  *starlet*                                     ...   
16  romanlily                                     ...   
17  Pandarine                                     ...   
18  jkottke                                  

Compare results using Kendall tau:

In [10]:
print("degree centrality <-> in degree centrality")
print(scipy.stats.kendalltau(list(df["degree centrality"]),list(df["in degree centrality"])))
print("degree centrality <-> out degree centrality")
print(scipy.stats.kendalltau(list(df["degree centrality"]),list(df["out degree centrality"])))
print("degree centrality <-> PageRank")
print(scipy.stats.kendalltau(list(df["degree centrality"]),list(df["PageRank"])))
print("degree centrality <-> hubs")
print(scipy.stats.kendalltau(list(df["degree centrality"]),list(df["hubs"])))
print("degree centrality <-> authorities")
print(scipy.stats.kendalltau(list(df["degree centrality"]),list(df["authorities"])))
print("in degree centrality <-> out degree centrality")
print(scipy.stats.kendalltau(list(df["in degree centrality"]),list(df["out degree centrality"])))
print("in degree centrality <-> PageRank")
print(scipy.stats.kendalltau(list(df["in degree centrality"]),list(df["PageRank"])))
print("in degree centrality <-> hubs")
print(scipy.stats.kendalltau(list(df["in degree centrality"]),list(df["hubs"])))
print("in degree centrality <-> authorities")
print(scipy.stats.kendalltau(list(df["in degree centrality"]),list(df["authorities"])))
print("out degree centrality <-> PageRank")
print(scipy.stats.kendalltau(list(df["out degree centrality"]),list(df["PageRank"])))
print("out degree centrality <-> hubs")
print(scipy.stats.kendalltau(list(df["out degree centrality"]),list(df["hubs"])))
print("out degree centrality <-> authorities")
print(scipy.stats.kendalltau(list(df["out degree centrality"]),list(df["authorities"])))
print("PageRank <-> hubs")
print(scipy.stats.kendalltau(list(df["PageRank"]),list(df["hubs"])))
print("PageRank <-> authorities")
print(scipy.stats.kendalltau(list(df["PageRank"]),list(df["authorities"])))
print("hubs <-> authorities")
print(scipy.stats.kendalltau(list(df["hubs"]),list(df["authorities"])))

degree centrality <-> in degree centrality
KendalltauResult(correlation=0.095510204081632688, pvalue=0.32773399859489416)
degree centrality <-> out degree centrality
KendalltauResult(correlation=0.092244897959183711, pvalue=0.34454202675886647)
degree centrality <-> PageRank
KendalltauResult(correlation=0.071020408163265339, pvalue=0.46677116365184501)
degree centrality <-> hubs
KendalltauResult(correlation=0.093877551020408193, pvalue=0.33607039158044105)
degree centrality <-> authorities
KendalltauResult(correlation=-0.054693877551020426, pvalue=0.57517563412134831)
in degree centrality <-> out degree centrality
KendalltauResult(correlation=-0.15591836734693884, pvalue=0.11011247719844237)
in degree centrality <-> PageRank
KendalltauResult(correlation=0.19836734693877558, pvalue=0.042086846362897411)
in degree centrality <-> hubs
KendalltauResult(correlation=0.129795918367347, pvalue=0.18351420234666738)
in degree centrality <-> authorities
KendalltauResult(correlation=0.079183673469

/usr/local/lib/python2.7/site-packages/scipy/stats/stats.py:257: RuntimeWarning: The input array could not be properly checked for nan values. nan values will be ignored.
  "values. nan values will be ignored.", RuntimeWarning)


### <hr /> Task 2

Here are the [Facebook friendship graphs](https://snap.stanford.edu/data/egonets-Facebook.html) from several US universities from 2005 (one year after fb launch).

Data contains a A matrix (sparse) and a "local_info" variable, one row per node: 
a student/faculty status flag, gender, major, second major/minor (if applicable), dorm/house, year, and high school. 
Missing data is coded 0.

Compute node degree assortativity (mixining by node degree) and assortativity coefficient (modularity) for gender, major, dormitory, year, high school for all universities and compare the results.

### Berkeley

Create graph:

In [11]:
data_B = scipy.io.loadmat('/Users/Evgenia/Desktop/Данные/universities/Berkeley13.mat')
G_B = nx.from_scipy_sparse_matrix(data_B["A"],create_using=nx.DiGraph())

Set attributes:

In [12]:
keys = [i for i in range (data_B["A"].shape[0])]
values_gender = [i[1] for i in data_B["local_info"]]
vg = dict(zip(keys, values_gender))
nx.set_node_attributes(G_B, 'gender',vg)

values_major = [i[2] for i in data_B["local_info"]]
vm = dict(zip(keys, values_major))
nx.set_node_attributes(G_B, 'major',vm)

values_dormitory = [i[4] for i in data_B["local_info"]]
vd = dict(zip(keys, values_dormitory))
nx.set_node_attributes(G_B, 'dormitory',vd)

values_year = [i[5] for i in data_B["local_info"]]
vy = dict(zip(keys, values_year))
nx.set_node_attributes(G_B, 'year',vy)

values_school = [i[1] for i in data_B["local_info"]]
vs = dict(zip(keys, values_school))
nx.set_node_attributes(G_B, 'school',vs)

Compute node degree assortativity (mixining by node degree):

In [13]:
degree_matrix_B=nx.degree_mixing_matrix(G_B)
degree_matrix_B

array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   1.40771711e-05,   4.69239035e-06, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   4.69239035e-06,   9.38478070e-06, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00]])

Compute assortativity coefficient:

In [14]:
print "Assortativity coefficient for gender = ",nx.attribute_assortativity_coefficient(G_B, "gender")
print "Assortativity coefficient for major = ",nx.attribute_assortativity_coefficient(G_B, "major")
print "Assortativity coefficient for dormitory = ",nx.attribute_assortativity_coefficient(G_B, "dormitory")
print "Assortativity coefficient for year = ",nx.attribute_assortativity_coefficient(G_B, "year")
print "Assortativity coefficient for school = ",nx.attribute_assortativity_coefficient(G_B, "school")

Assortativity coefficient for gender =  0.0409228376393
Assortativity coefficient for major =  0.058255029946
Assortativity coefficient for dormitory =  0.14727644076
Assortativity coefficient for year =  0.308121015806
Assortativity coefficient for school =  0.0409228376393


### Caltech

Create graph:

In [15]:
data_C = scipy.io.loadmat('/Users/Evgenia/Desktop/Данные/universities/Caltech36.mat')
G_C = nx.from_scipy_sparse_matrix(data_C["A"],create_using=nx.DiGraph())

Set attributes:

In [16]:
keys = [i for i in range (data_C["A"].shape[0])]
values_gender = [i[1] for i in data_C["local_info"]]
vg = dict(zip(keys, values_gender))
nx.set_node_attributes(G_C, 'gender',vg)

values_major = [i[2] for i in data_C["local_info"]]
vm = dict(zip(keys, values_major))
nx.set_node_attributes(G_C, 'major',vm)

values_dormitory = [i[4] for i in data_C["local_info"]]
vd = dict(zip(keys, values_dormitory))
nx.set_node_attributes(G_C, 'dormitory',vd)

values_year = [i[5] for i in data_C["local_info"]]
vy = dict(zip(keys, values_year))
nx.set_node_attributes(G_C, 'year',vy)

values_school = [i[1] for i in data_C["local_info"]]
vs = dict(zip(keys, values_school))
nx.set_node_attributes(G_C, 'school',vs)

Compute node degree assortativity (mixining by node degree):

In [17]:
degree_matrix_C=nx.degree_mixing_matrix(G_C)
degree_matrix_C

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.00012008,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.00030019, ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

Compute assortativity coefficient:

In [18]:
print "Assortativity coefficient for gender = ",nx.attribute_assortativity_coefficient(G_C, "gender")
print "Assortativity coefficient for major = ",nx.attribute_assortativity_coefficient(G_C, "major")
print "Assortativity coefficient for dormitory = ",nx.attribute_assortativity_coefficient(G_C, "dormitory")
print "Assortativity coefficient for year = ",nx.attribute_assortativity_coefficient(G_C, "year")
print "Assortativity coefficient for school = ",nx.attribute_assortativity_coefficient(G_C, "school")

Assortativity coefficient for gender =  0.0463314364559
Assortativity coefficient for major =  0.0347194237236
Assortativity coefficient for dormitory =  0.349153100873
Assortativity coefficient for year =  0.237531904813
Assortativity coefficient for school =  0.0463314364559


### Harvard

Create graph:

In [19]:
data_H = scipy.io.loadmat('/Users/Evgenia/Desktop/Данные/universities/Harvard1.mat')
G_H = nx.from_scipy_sparse_matrix(data_H["A"],create_using=nx.DiGraph())

Set attributes:

In [20]:
keys = [i for i in range (data_H["A"].shape[0])]
values_gender = [i[1] for i in data_H["local_info"]]
vg = dict(zip(keys, values_gender))
nx.set_node_attributes(G_H, 'gender',vg)

values_major = [i[2] for i in data_H["local_info"]]
vm = dict(zip(keys, values_major))
nx.set_node_attributes(G_H, 'major',vm)

values_dormitory = [i[4] for i in data_H["local_info"]]
vd = dict(zip(keys, values_dormitory))
nx.set_node_attributes(G_H, 'dormitory',vd)

values_year = [i[5] for i in data_H["local_info"]]
vy = dict(zip(keys, values_year))
nx.set_node_attributes(G_H, 'year',vy)

values_school = [i[1] for i in data_H["local_info"]]
vs = dict(zip(keys, values_school))
nx.set_node_attributes(G_H, 'school',vs)

Compute node degree assortativity (mixining by node degree):

In [21]:
degree_matrix_H=nx.degree_mixing_matrix(G_H)
degree_matrix_H

array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   2.06156313e-05,   1.21268419e-05, ...,
          0.00000000e+00,   0.00000000e+00,   6.06342096e-07],
       [  0.00000000e+00,   1.21268419e-05,   2.18283154e-05, ...,
          0.00000000e+00,   0.00000000e+00,   6.06342096e-07],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   6.06342096e-07,   6.06342096e-07, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00]])

Compute assortativity coefficient:

In [22]:
print "Assortativity coefficient for gender = ",nx.attribute_assortativity_coefficient(G_H, "gender")
print "Assortativity coefficient for major = ",nx.attribute_assortativity_coefficient(G_H, "major")
print "Assortativity coefficient for dormitory = ",nx.attribute_assortativity_coefficient(G_H, "dormitory")
print "Assortativity coefficient for year = ",nx.attribute_assortativity_coefficient(G_H, "year")
print "Assortativity coefficient for school = ",nx.attribute_assortativity_coefficient(G_H, "school")

Assortativity coefficient for gender =  0.0452699773794
Assortativity coefficient for major =  0.0496769283286
Assortativity coefficient for dormitory =  0.12567663505
Assortativity coefficient for year =  0.421159642116
Assortativity coefficient for school =  0.0452699773794


### Oklahoma

Create graph:

In [23]:
data_O = scipy.io.loadmat('/Users/Evgenia/Desktop/Данные/universities/Oklahoma97.mat')
G_O = nx.from_scipy_sparse_matrix(data_O["A"],create_using=nx.DiGraph())

Set attributes:

In [24]:
keys = [i for i in range (data_O["A"].shape[0])]
values_gender = [i[1] for i in data_O["local_info"]]
vg = dict(zip(keys, values_gender))
nx.set_node_attributes(G_O, 'gender',vg)

values_major = [i[2] for i in data_O["local_info"]]
vm = dict(zip(keys, values_major))
nx.set_node_attributes(G_O, 'major',vm)

values_dormitory = [i[4] for i in data_O["local_info"]]
vd = dict(zip(keys, values_dormitory))
nx.set_node_attributes(G_O, 'dormitory',vd)

values_year = [i[5] for i in data_O["local_info"]]
vy = dict(zip(keys, values_year))
nx.set_node_attributes(G_O, 'year',vy)

values_school = [i[1] for i in data_O["local_info"]]
vs = dict(zip(keys, values_school))
nx.set_node_attributes(G_O, 'school',vs)

Compute node degree assortativity (mixining by node degree):

In [25]:
degree_matrix_O=nx.degree_mixing_matrix(G_O)
degree_matrix_O

array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   1.12041303e-06,   3.92144560e-06, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   3.92144560e-06,   7.84289120e-06, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00]])

Compute assortativity coefficient:

In [26]:
print "Assortativity coefficient for gender = ",nx.attribute_assortativity_coefficient(G_O, "gender")
print "Assortativity coefficient for major = ",nx.attribute_assortativity_coefficient(G_O, "major")
print "Assortativity coefficient for dormitory = ",nx.attribute_assortativity_coefficient(G_O, "dormitory")
print "Assortativity coefficient for year = ",nx.attribute_assortativity_coefficient(G_O, "year")
print "Assortativity coefficient for school = ",nx.attribute_assortativity_coefficient(G_O, "school")

Assortativity coefficient for gender =  0.0928372959827
Assortativity coefficient for major =  0.0363790887617
Assortativity coefficient for dormitory =  0.280335243729
Assortativity coefficient for year =  0.20116469147
Assortativity coefficient for school =  0.0928372959827


### Princeton

Create graph:

In [27]:
data_P = scipy.io.loadmat('/Users/Evgenia/Desktop/Данные/universities/Princeton12.mat')
G_P = nx.from_scipy_sparse_matrix(data_P["A"],create_using=nx.DiGraph())

Set attributes:

In [28]:
keys = [i for i in range (data_P["A"].shape[0])]
values_gender = [i[1] for i in data_P["local_info"]]
vg = dict(zip(keys, values_gender))
nx.set_node_attributes(G_P, 'gender',vg)

values_major = [i[2] for i in data_P["local_info"]]
vm = dict(zip(keys, values_major))
nx.set_node_attributes(G_P, 'major',vm)

values_dormitory = [i[4] for i in data_P["local_info"]]
vd = dict(zip(keys, values_dormitory))
nx.set_node_attributes(G_P, 'dormitory',vd)

values_year = [i[5] for i in data_P["local_info"]]
vy = dict(zip(keys, values_year))
nx.set_node_attributes(G_P, 'year',vy)

values_school = [i[1] for i in data_P["local_info"]]
vs = dict(zip(keys, values_school))
nx.set_node_attributes(G_P, 'school',vs)

Compute node degree assortativity (mixining by node degree):

In [29]:
degree_matrix_P=nx.degree_mixing_matrix(G_P)
degree_matrix_P

array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   2.04554752e-05,   1.19323606e-05, ...,
          0.00000000e+00,   0.00000000e+00,   1.70462294e-06],
       [  0.00000000e+00,   1.19323606e-05,   1.36369835e-05, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   1.70462294e-06,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00]])

Compute assortativity coefficient:

In [30]:
print "Assortativity coefficient for gender = ",nx.attribute_assortativity_coefficient(G_P, "gender")
print "Assortativity coefficient for major = ",nx.attribute_assortativity_coefficient(G_P, "major")
print "Assortativity coefficient for dormitory = ",nx.attribute_assortativity_coefficient(G_P, "dormitory")
print "Assortativity coefficient for year = ",nx.attribute_assortativity_coefficient(G_P, "year")
print "Assortativity coefficient for school = ",nx.attribute_assortativity_coefficient(G_P, "school")

Assortativity coefficient for gender =  0.0506107399953
Assortativity coefficient for major =  0.0543901188714
Assortativity coefficient for dormitory =  0.0946784195542
Assortativity coefficient for year =  0.446744620584
Assortativity coefficient for school =  0.0506107399953


### Texas

Create graph:

In [31]:
data_T = scipy.io.loadmat('/Users/Evgenia/Desktop/Данные/universities/Texas80.mat')
G_T = nx.from_scipy_sparse_matrix(data_T["A"],create_using=nx.DiGraph())

Set attributes:

In [32]:
keys = [i for i in range (data_T["A"].shape[0])]
values_gender = [i[1] for i in data_T["local_info"]]
vg = dict(zip(keys, values_gender))
nx.set_node_attributes(G_T, 'gender',vg)

values_major = [i[2] for i in data_T["local_info"]]
vm = dict(zip(keys, values_major))
nx.set_node_attributes(G_T, 'major',vm)

values_dormitory = [i[4] for i in data_T["local_info"]]
vd = dict(zip(keys, values_dormitory))
nx.set_node_attributes(G_T, 'dormitory',vd)

values_year = [i[5] for i in data_T["local_info"]]
vy = dict(zip(keys, values_year))
nx.set_node_attributes(G_T, 'year',vy)

values_school = [i[1] for i in data_T["local_info"]]
vs = dict(zip(keys, values_school))
nx.set_node_attributes(G_T, 'school',vs)

Compute node degree assortativity (mixining by node degree):

In [33]:
degree_matrix_T=nx.degree_mixing_matrix(G_T)
degree_matrix_T

array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   9.01898086e-06,   1.63981470e-06, ...,
          0.00000000e+00,   0.00000000e+00,   4.09953675e-07],
       [  0.00000000e+00,   1.63981470e-06,   4.91944410e-06, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   4.09953675e-07,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00]])

Compute assortativity coefficient:

In [34]:
print "Assortativity coefficient for gender = ",nx.attribute_assortativity_coefficient(G_T, "gender")
print "Assortativity coefficient for major = ",nx.attribute_assortativity_coefficient(G_T, "major")
print "Assortativity coefficient for dormitory = ",nx.attribute_assortativity_coefficient(G_T, "dormitory")
print "Assortativity coefficient for year = ",nx.attribute_assortativity_coefficient(G_T, "year")
print "Assortativity coefficient for school = ",nx.attribute_assortativity_coefficient(G_T, "school")

Assortativity coefficient for gender =  0.0796930681412
Assortativity coefficient for major =  0.0597127278334
Assortativity coefficient for dormitory =  0.204837604339
Assortativity coefficient for year =  0.246194684162
Assortativity coefficient for school =  0.0796930681412


### Compare result:

In [35]:
df={"for gender":[nx.attribute_assortativity_coefficient(G_B, "gender"),\
                 nx.attribute_assortativity_coefficient(G_C, "gender"),\
                 nx.attribute_assortativity_coefficient(G_H, "gender"),\
                 nx.attribute_assortativity_coefficient(G_O, "gender"),\
                 nx.attribute_assortativity_coefficient(G_P, "gender"),\
                 nx.attribute_assortativity_coefficient(G_T, "gender")],
   "for major":[nx.attribute_assortativity_coefficient(G_B, "major"),\
                 nx.attribute_assortativity_coefficient(G_C, "major"),\
                 nx.attribute_assortativity_coefficient(G_H, "major"),\
                 nx.attribute_assortativity_coefficient(G_O, "major"),\
                 nx.attribute_assortativity_coefficient(G_P, "major"),\
                 nx.attribute_assortativity_coefficient(G_T, "major")],
   "for dormitory":[nx.attribute_assortativity_coefficient(G_B, "dormitory"),\
                 nx.attribute_assortativity_coefficient(G_C, "dormitory"),\
                 nx.attribute_assortativity_coefficient(G_H, "dormitory"),\
                 nx.attribute_assortativity_coefficient(G_O, "dormitory"),\
                 nx.attribute_assortativity_coefficient(G_P, "dormitory"),\
                 nx.attribute_assortativity_coefficient(G_T, "dormitory")],
   "for year":[nx.attribute_assortativity_coefficient(G_B, "year"),\
                 nx.attribute_assortativity_coefficient(G_C, "year"),\
                 nx.attribute_assortativity_coefficient(G_H, "year"),\
                 nx.attribute_assortativity_coefficient(G_O, "year"),\
                 nx.attribute_assortativity_coefficient(G_P, "year"),\
                 nx.attribute_assortativity_coefficient(G_T, "year")],
   "for school":[nx.attribute_assortativity_coefficient(G_B, "school"),\
                 nx.attribute_assortativity_coefficient(G_C, "school"),\
                 nx.attribute_assortativity_coefficient(G_H, "school"),\
                 nx.attribute_assortativity_coefficient(G_O, "school"),\
                 nx.attribute_assortativity_coefficient(G_P, "school"),\
                 nx.attribute_assortativity_coefficient(G_T, "school")]}

In [36]:
df=pd.DataFrame(df,index=["Berkeley","Caltech","Harvard","Oklahoma","Princeton","Texas"])
df

for dormitory  for gender  for major  for school  for year
Berkeley        0.147276    0.040923   0.058255    0.040923  0.308121
Caltech         0.349153    0.046331   0.034719    0.046331  0.237532
Harvard         0.125677    0.045270   0.049677    0.045270  0.421160
Oklahoma        0.280335    0.092837   0.036379    0.092837  0.201165
Princeton       0.094678    0.050611   0.054390    0.050611  0.446745
Texas           0.204838    0.079693   0.059713    0.079693  0.246195